server:
  port: 18098 # port

spring:
  application:
    name: table # ???????

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18082/eureka/
  instance:
    prefer-ip-address: true



