server:
  port: 18098 # port

spring:
  application:
    name: table # ???????
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@106.14.212.200:1521:XE
    hikari:
      username: yang
      password: yx123
  jpa:
    database: oracle

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18082/eureka/
  instance:
    prefer-ip-address: true







