server:
  port: 18083 # port

spring:
  application:
    name: asset
  datasource:
    url: jdbc:oracle:thin:@106.14.212.200:1521:XE
    username: yang
    password: yx123

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18082/eureka/
  instance:
    prefer-ip-address: true

