server:
  port: 18094 # port

spring:
  application:
    name: promotion

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18082/eureka/
  instance:
    prefer-ip-address: true


