server:
  port: 18088 # port

spring:
  application:
    name: ingredientRecords

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18082/eureka/
  instance:
    prefer-ip-address: true
